### PR TITLE
Introducing issuescreate

### PR DESCRIPTION
**Pull request by wenlock**
Hey 👋🏽 Sorry for the PR out of the blue. Wanted to share this in case it's of any interest. I'm pushing it here since I borrowed most of the logic from `behest` and thought that I'd share it back and let y'all decide if you want it or not.

Thanks for the pointers/help on actions and create issues @froi @Chocrates. This will likely be used internally for some project work we're managing on fan out activities.

It's useful for creating issues on **N** repos from a single tracking/reference issue. The command kinda looks like this in an issue comment:

```
/issuescreate bhest.md
https://github.com/wenlock/test-repo-1
https://github.com/wenlock/test-repo-2
/endissuescreate
```

I've setup a run of it [over here if you want to see the results](https://github.com/wenlock/test-repo-0/issues/5). 

This is a great resource, thanks for the ActionDesk org! 🎉

### CODE REVIEW

**Comment by froi** [comment]
Hey @wenlock 👋🏼

Thanks for the PR ❤️. We’ll take a look at it soon!

**Comment by wenlock** [comment]
cool is the merge process just click merge?

**Comment by Chocrates** [comment]
@jasonmacgowan any objections?

**Comment by jasonmacgowan** [comment]
Yeah let's merge it!

**Pull request merged**
